name: agha_db
description: A Mock Database Like Real Firebase ForeStore .
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  hive:  
  uuid: 
  path_provider:


dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
